+---------------------------+-----------------+--------------------------------+---------------------------+----------------------------------------------------+-----------------+-----------------+
|         TIMESTAMP         |       TASK      |            FUNCTION            |            FILE           |                       MESSAGE                      |   PROCESS_TYPE  |      STATUS     |
+---------------------------+-----------------+--------------------------------+---------------------------+----------------------------------------------------+-----------------+-----------------+
| 2025-10-03 07:45:06       | IMP_DOC_QUALIS_ | connect                        | databasesrc.py            | dcConfig disponível: ['dbconnstr', 'dbschema',     | system          | information     |
|                           |                 |                                |                           | 'projectname', 'folderlog', 'logtablename',        |                 |                 |
|                           |                 |                                |                           | 'databasename', 'tabdocumentosged', 'url_inicial', |                 |                 |
|                           |                 |                                |                           | 'url_api_processo', 'database']                    |                 |                 |
| 2025-10-03 07:45:07       | IMP_DOC_QUALIS_ | connect                        | databasesrc.py            | :::Processo de Conexão Iniciado:::                 | system          | information     |
| 2025-10-03 07:45:09       | IMP_DOC_QUALIS_ | connect                        | databasesrc.py            | Conectado com sucesso ao PostgreSQL: PostgreSQL    | system          | success         |
|                           |                 |                                |                           | 17.6 on aarch64-unknown-linux-gnu, comp            |                 |                 |
| 2025-10-03 07:45:10       | IMP_DOC_QUALIS_ | verifica_arq_existe            | planilha_processar.py     | Não existe arquivo .xlsx na pasta                  | system          | critical        |
|                           |                 |                                |                           | data\input\Capturados - LN 279 em                  |                 |                 |
|                           |                 |                                |                           | planilha_processar.py                              |                 |                 |
+---------------------------+-----------------+--------------------------------+---------------------------+----------------------------------------------------+-----------------+-----------------+
| 2025-10-03 07:45:10       | IMP_DOC_QUALIS_ | Main                           | main.py                   | Planilha de Processamento não encontrada ou Vazia  | system          | critical        |
|                           |                 |                                |                           | - LN 22 em main.py                                 |                 |                 |
+---------------------------+-----------------+--------------------------------+---------------------------+----------------------------------------------------+-----------------+-----------------+
| 2025-10-03 07:45:11       | IMP_DOC_QUALIS_ | executar_acesso_sharepoint     | sharepoint_acesso.py      | === TENTATIVA 1 DE 3 ===                           | system          | information     |
| 2025-10-03 07:45:11       | IMP_DOC_QUALIS_ | _inicializar_navegador         | sharepoint_acesso.py      | Abrindo o navegador                                | system          | information     |
| 2025-10-03 07:45:18       | IMP_DOC_QUALIS_ | confere_conexao_do_banco       | sharepoint_acesso.py      | db_manager está conectado                          | system          | information     |
| 2025-10-03 07:45:18       | IMP_DOC_QUALIS_ | _obter_links_do_banco          | sharepoint_acesso.py      | Pesquisando pelo status: PENDENTE                  | system          | information     |
| 2025-10-03 07:45:19       | IMP_DOC_QUALIS_ | _obter_links_do_banco          | sharepoint_acesso.py      | 154 links obtidos do banco                         | system          | information     |
| 2025-10-03 07:45:19       | IMP_DOC_QUALIS_ | _acessar_sharepoint            | sharepoint_acesso.py      | Acessando URL: https://fibrasacombr.sharepoint.com | system          | information     |
|                           |                 |                                |                           | /sites/GED/Documentos%20Compartilhados/1.Corporati |                 |                 |
|                           |                 |                                |                           | vo%20-%20FICORP/Publicados                         |                 |                 |
| 2025-10-03 07:45:20       | IMP_DOC_QUALIS_ | _acessar_sharepoint            | sharepoint_acesso.py      | Erro ao acessar URL: Page.goto: net::ERR_ABORTED;  | system          | failure         |
|                           |                 |                                |                           | maybe frame was detached? Call log:   - navigating |                 |                 |
|                           |                 |                                |                           | to "https://fibrasacombr.sharepoint.com/sites/GED/ |                 |                 |
|                           |                 |                                |                           | Documentos%20Compartilhados/1.Corporativo%20-      |                 |                 |
|                           |                 |                                |                           | %20FICORP/Publicados", waiting until "load"  - LN  |                 |                 |
|                           |                 |                                |                           | 134 em sharepoint_acesso.py                        |                 |                 |
| 2025-10-03 07:45:21       | IMP_DOC_QUALIS_ | executar_acesso_sharepoint     | sharepoint_acesso.py      | Erro geral: Falha ao acessar primeiro link - LN    | system          | failure         |
|                           |                 |                                |                           | 253 em sharepoint_acesso.py                        |                 |                 |
| 2025-10-03 07:45:23       | IMP_DOC_QUALIS_ | _finalizar_navegador           | sharepoint_acesso.py      | Recursos finalizados com sucesso                   | system          | information     |
| 2025-10-03 07:45:24       | IMP_DOC_QUALIS_ | executar_acesso_sharepoint     | sharepoint_acesso.py      | Tentando novamente...                              | system          | information     |
+---------------------------+-----------------+--------------------------------+---------------------------+----------------------------------------------------+-----------------+-----------------+
